### ISSUE TITLE
Not use flask?

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/PythonPlugin#1]
I feel like flask is a bad choice here, as it's already a good HTTP library that doesn't need this kinda framework around it. I think the built-in python HTTP library would be a much better choice.

**Comment by JBYT27** [comment]
Okay, thanks for the suggestion? So what lib should I use instead (or suggestion for lib?)?

**Comment by darkdarcool** [comment]
> Okay, thanks for the suggestion? So what lib should I use instead (or suggestion for lib?)?

As I said in my initial comment, I think the builtin python HTTP library would be good, you can find the docs [here](https://docs.python.org/3/library/http.client.html)

**Comment by JBYT27** [comment]
Oh, okay, I didn't understand what you meant by that. Thanks!

**Comment by darkdarcool** [comment]
You're welcome!
